[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "3d0405e47df4b51646e238ed366989e6ee57cf94"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "ee30ceacc51e8fac605e66ddeaa83a3c7a650641c8789d6c53fdd28ae59e7649"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.aarch64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "1f76852c58fe9762d66840bb9826efb4490f8a18"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "84ad397671573cdf660fab9f8715c56c866a9498af8444a70c6c257695e6d61a"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.aarch64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "1aaa5aac04682770dbb33bc022772c97e9e18fcf"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "99ef390c7e808dbe4b04e93ad46ffbbe9654ef78ac107832a7d35922e30ba200"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.aarch64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "c504d67f802d383411c73001008309429b3dd80c"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "89d2e2425cb95bdd40238729e0143a527fdd012328abb114827b0f858e8d73b0"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.aarch64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee0b9e6409b320e447b4db6178570a5c2b187482"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "4f8f3c913ffb4a1a4f8bbc86671193a0fb7f0796f1ee10a4939d780ffd03e3d5"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.armv6l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aae9d6e31069e71070a36906492ac3a4f4b63464"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "9cc11af277a6e7b963a2564b93ae031c76ca7f08ecfbcfe81abad6ac0ee18284"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.armv6l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "57155d553c60f3a7801f29cd8c78f71a8d1d6bac"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "7834d5c58b3a6a3e856abfb9e735ae757a446b123ed9ecc37dcea6e1d37a154e"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.armv7l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "772c0d906ee5a1829e19d2cd23587b2d7cdc9d92"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "e4686a4d89be3ffd653c49d76908a7d5344e045b1a82a89a4a876c6e6684f577"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.armv7l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "361c1ad4d52c91c16356455a0507c007df8a14c6"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "9a25d68576e4e7760525a6cd95e8718d9e677b37a92b400e4993a92c48319075"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.i686-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "fe47249987f26a40cdc87069d9e7367eeffe5341"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "c1b3c84a247e5f1fc013749d390f7c6597e4e7bf49fd80de7bc2993df51c5b6e"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.i686-linux-musl.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "3ca9399c177b3f9519ad99525a1112622bffb419"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "48e878d4b397a5772daec8e6df9a83fbf3ddebc7df60928735da15df75bfdad1"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.i686-w64-mingw32.tar.gz"
[[LittleCMS]]
arch = "powerpc64le"
git-tree-sha1 = "65ff0b32dbc0ee2b03a75967a82ba8680e2799bf"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "06b530b34b570138c19ab0384b853b2c9063c613dee6e63ce34c140dfd35932f"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.powerpc64le-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "riscv64"
git-tree-sha1 = "a1ab73b4ed257e4a3c6bac2aca957043468b2726"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "a32a8ac2d2c5217335fe80abcbfa60739f081809a7383ba2e663dc169bbf87d4"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.riscv64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "4313ef033bac63ba494b299bb6422f87a9eb39d2"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "06d2cb28eb928dc00a54bf42a2fe58cad0ac7b2a1c508f4c65baaabe9058c1ee"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.x86_64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "4af293b21d9075de1ab1d1800bb93c22aeb9eed1"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "d2ea0d741c38f3eace35b196a4b799d1b551cf305033bde923884f3121acc88a"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.x86_64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "19813670e07bbb6d172cfa7a9170a4a24af23a70"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "70b1e9fcc5be71544e064031f00f39f459f8d5d6d02dabe18dd9e1b0b236be97"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.x86_64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "65328b025151b36a915079bdb7d8593eb24bc54c"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "4427a42fbd7d4845e7b415b7b74ad428f3eb3c4e189d1fa00b46c69df388b7d5"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.x86_64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "98b27166218c5c4d6d2a0f8f654a8595d2790e81"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "6251cdebef12bbfce530fdc3db43760a9529d0d669d8855d269ccce1ae5edd21"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.1+0/LittleCMS.v2.19.1.x86_64-w64-mingw32.tar.gz"
