[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "19f879c1049a5ea03309520eb4ff5d17ac69833a"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "b1bf0cea04025538b75ef27b98658cfdaf62a8c273351e73385c7dac14e97b2a"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.aarch64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "f93b79d686d5e582fd308804dcc08bbe14c76507"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "021c757df3b11a319c12b0b4d17135803e88112c27df917dc82e0b7da03274e8"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.aarch64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "45366f9f60bde36561fa41d12a6dfff6f43d7f3d"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "a660a3a92211bf898e606f4a5972cd6de76e03605966c47e3db05d20ed2115bf"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.aarch64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "24a6663abd631f498d72b12108b027ef73c33755"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "6ad9ef414facabfe7de115b42f74310c90bd218e5a9bbd0bc66b24a342aae0f6"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.aarch64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8c88019e326c7d0168b22c7640ddec03d97c0e46"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "e0f04efec94913dd82411e2b6da36974fc3fe052a5a6e2cb52b7b4de6e1b19d1"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.armv6l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7189cffdbf02007437e3f36b9a315641ab4266a7"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "c646ca2df1aa518a8d7672bd52382fddf844d491672c7afd5305515b8e39f898"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.armv6l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ca07086019ad7d2afcc5f69e460d6f16ad53de6"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "b8cc89f4b54d9fd3652e2ca182a3ce770ea605c189be7e89d52b61b348966e3d"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.armv7l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98bcb4e574209500185ee9be6cf34ae3ff984b8d"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "da64711d974856a5bc98e2dd73b08c1457d6bddd720e47916d552f27380cdb77"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.armv7l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "eb09e8f15a802d7e044361c689a476a662da67e8"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "10b30588a72d609eee9701fbcb1b578b7198c47d49c3b74aa658f4dc56f6ca2d"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.i686-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "223e95bdd36897fe25f6c9777eeb9fda05565120"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "9610fe5a96cb96671d75a5fd35916a8658f9545e5fa71d1337f701cbf23088d3"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.i686-linux-musl.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "97d93988d650ccd3804214d9e1609e1ad8f4d3be"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "ec981e439f7a75dd07d3f8477f338451d9cc3bc94614d6be05b6749bde1d6940"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.i686-w64-mingw32.tar.gz"
[[LittleCMS]]
arch = "powerpc64le"
git-tree-sha1 = "517a9fee163a7409a3bd7de82aecba0b8292b83d"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "1500d8362183ea794de8a70453e2524c33e55576e82c50cd819d5bc976ce6a7e"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.powerpc64le-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "riscv64"
git-tree-sha1 = "054d5a38a2d46ab6691ffcda8669aaf9071437b8"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "14c84eb6eda580245d819ba92943e5fe298e7990ea0dc46739fca67b5d831789"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.riscv64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "31be2a4a3cde093e4a2307eff7c52225c9004996"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "be2479d549061a2591ebf7aa933d8e4d25bf4b664bcac451bb23783e33263a87"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.x86_64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "d2edd53a2bb47c1ededc026ffd8780718e455a9a"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "4cea14c9b61c4244d6baa53793e85b8a124cbe835c182e4c6fb1f03977183d10"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.x86_64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "4fd536279303ad9a2c3b14637ca466c80f0878a7"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "104c652b02fcd63b2f0a6c36375e849202e4dfdeb502dcd0eaa4d29aa9b1b274"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.x86_64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "05fa50b8ae8d68e8011546b14b02cbbb6d0a0bda"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "d64260daa7ac74d9f05715b09148552c1162d3c656240e8dbb248291ece311d8"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.x86_64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "19e7b706f68b4b6ea060ff735613bafc940867bf"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "1185900677b12d9efe52858272094fbe8ced6f796aeb719788a1a6da08f6d11e"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.17.0+0/LittleCMS.v2.17.0.x86_64-w64-mingw32.tar.gz"
