[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "c74b82ff580cf9830aff2ad6c01a01a5594545bf"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "2d3ded9cc68a51f2031037bb1ca5227f8e1e152f79c694b525cb4de72cf6fae9"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.aarch64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "c1c9e3a28335e0d45d476ab66635ea363ac3b7d4"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "f07e4254d4f6e197eb3ddee902c049c6dea4ef53cc47743918330df2abaeef84"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.aarch64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "933cf2b9d4bac2ac5858f8f9794c1f0ffc527aa7"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "06856708ff3b054575280f53cfb56b7e1b456699838fd5e9d2f8c45a8415b22f"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.aarch64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "be8f71532d8770003fbcf925fa6145d57da835bf"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "11e0b834a1bd91577602718f12bdfb25146b33cfa2582c3371170feaaf016499"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.aarch64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "15d384f0bd447a0a2015a187f0e08640295f85ed"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "13bdf0f7f289062d1fd540e344c3d086c6a86575ffc74ac9f397b8be25f26696"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.armv6l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0691320e9fa72303d7c23f4b580b7ded360302f4"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "1ee786ce3c087d293dd92d5bf0cffe46fe9401d2ba0ccded72b8c96ae854d1c8"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.armv6l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07de4aa0cf04092536cb5e58b0a269e0d882cff1"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "9b2ba6b96a2721a7dfcd1e35d60455b562634b4095efc1c1183c0a4acb750284"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.armv7l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bd70f6911cee24cac86bfc4030354a608eff0e1c"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "eb3a6b29933aba0a3068ddcd4a5a8eae54ab1ed2a57505d609fbff8526b6f2e5"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.armv7l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "8ce0d223b96fec58d035bc20e0bf2df55c3b99a2"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "a35d445e6581ee5eacd8402d4cb153ad1dde2341735aeacd5993f105e3fb5592"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.i686-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "303112b15628879b07917e6f8f90e0e4af909ff4"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "4e1119c4c5fcb05c9084360f3997ae38dca1840c0557641ab7a22d3f7e2472bc"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.i686-linux-musl.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "024cb87bc566801d63b82bd1decfaaa2235981c5"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "5966904a4cdc8a6089fe0172dcba107e386d13ce1232a2350565a0f4d07ae453"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.i686-w64-mingw32.tar.gz"
[[LittleCMS]]
arch = "powerpc64le"
git-tree-sha1 = "2a8c604c689cc32f907e5136748558e0b3a1de62"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "4609f52a23ed184adaa26ee0dcf7ed4cfeeeb5a6010ea618fbf32b1a200405b4"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.powerpc64le-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "riscv64"
git-tree-sha1 = "04d0068037d0f4ae17824e2ad9a953c55e340df8"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "150ba3629c1d1d87e9d95bf8bc2e6430195c8f676cf894cfe6f0b708cb61a077"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.riscv64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "8cfc322b0e25fda309d5d27eeb099c62bca96319"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "23e87f2e41be7707a3afcfdf822af0a2a63f6c5b90b7d6319f50fc93c4afa701"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.x86_64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "0dd8eee46276c54b75239a462f89a8e6f8a9a99a"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "9cddd4f21c190fffba4f0bfa2c7df9e64af8c6d2e428781415676dda40825038"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.x86_64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "a78f9b865c28419a37503958596dbd1eb84f8d91"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "9cf5db3b91715086290fa730f85196e1fb8ad291add4627c33f4de9ec20f289f"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.x86_64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "464bcead81df249bee441e20ccbfcf61abb46d5d"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "97f57dd0a110cae73c979025851b286590bea1b05431f0e113030a629c85cae0"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.x86_64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "fa0576f1c170695c544809305a0eb8b92e23cc76"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "f6706f4d4b8ef7b85a3e4f39d7f618671dd54e304f9c574143eeb4a9f664af25"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.19.0+0/LittleCMS.v2.19.0.x86_64-w64-mingw32.tar.gz"
