[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "7a574d719b2ca3fdce11d60df27feaed2926e8fe"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "6d5bf99e564d7c1c316b16f5bfe8f3742eb786d1123d945594b58f025829cf83"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.aarch64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "6833d2000bb7a596b09497b174e2a7070beee4b5"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "66dcfe11ff3e1a094a87c0e622acbc6ef9e98884bfe221034df5be0ba456d8df"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.aarch64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "aarch64"
git-tree-sha1 = "84cfcae43a76c071b2ed61a0cc187b9de88a5671"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "6d5dbe4f695cf9f0653eabda1751a31f4d3067f2af1264014d44f700d418537e"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.aarch64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4036c122d3fc7ee3b384f17d9b99bdd894ff41a1"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "7d55c2274e52d253f694f7c73a280491b272579f3a5048f62bba66c3ab273446"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.armv6l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2bd23b86482f7a8e4d6388aabf094563a097256"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "4a25f5cb8400e5c497692ea101ed236439fa4e14d68f0804e0b79211cb54583a"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.armv6l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9fa4d83f5bcbbab3e916afbcbc1099f25877872e"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "79e5acbd2b2f834656389ddb4423e99749e0c7a9bca34080a81d2496dd823c85"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.armv7l-linux-gnueabihf.tar.gz"
[[LittleCMS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7adc165f812f4ba60b114b3e1109be98155c3e77"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "ff061ae1f526a4e84ffb0863b4b6195af2d39d076f6637d6a2bf2a24d43291fe"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.armv7l-linux-musleabihf.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "9c87b2c58ef556f5b25d74b8ae9166adc2cd1271"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "5b8ab44d8acb96a8414a5f55da262995064fae5836d1526dffce25f6e7b9e034"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.i686-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "53866927b8fbc158735513846de385a390386dfd"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "84118abe78fe012507a45c0523c665a0d469dda91629352b1492f7e4ff1fb889"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.i686-linux-musl.tar.gz"
[[LittleCMS]]
arch = "i686"
git-tree-sha1 = "bda614d4da831edcde23e05cb07e0a929e4de024"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "2ba7724ccd8a6a702a09c88b859aa1b81e74ee8f22c498998e05ffd316a840da"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.i686-w64-mingw32.tar.gz"
[[LittleCMS]]
arch = "powerpc64le"
git-tree-sha1 = "cb14973d432633dc326127b17466ce88555d1d3c"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "40e7e557c59d58678830740801ce63144fc12eaa79606d899af4ff18fb4dd9b4"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.powerpc64le-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "ce8891bbdc2ff50f5fe2ac1d1fc217d5eb0c8e0f"
os = "macos"

    [[LittleCMS.download]]
    sha256 = "3c4cb6bc752d4e6277e89fce93518b24724bd3319c6fb2a2b50bc152104e2f79"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.x86_64-apple-darwin.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "4c6becd43e12ccc8bf20df6a88bdfb112caf592e"
libc = "glibc"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "e6c6b6f84949776d50c8a4b7533871588b91fd3290e016b1d6f79dcc1f8f49d8"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.x86_64-linux-gnu.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "fa985490edf2f9e5710fbad55d71169ee0745d0d"
libc = "musl"
os = "linux"

    [[LittleCMS.download]]
    sha256 = "e0f2eb89303be45ff50408e6402d073a66d9d1cbde025997ff6310d4c55bf64f"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.x86_64-linux-musl.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "3421e718366405ec0a2d17128edc90467454af1f"
os = "freebsd"

    [[LittleCMS.download]]
    sha256 = "9accc05d2854d603b61f23ef3190d42e0fe72006f608668fd3ed47d1919bcec5"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.x86_64-unknown-freebsd.tar.gz"
[[LittleCMS]]
arch = "x86_64"
git-tree-sha1 = "dab246038bc6c570335838bd565a473d3086b734"
os = "windows"

    [[LittleCMS.download]]
    sha256 = "f48b1393a2808d84785c948f1a79d03b370f40eea2bace317974fb499528d62a"
    url = "https://github.com/JuliaBinaryWrappers/LittleCMS_jll.jl/releases/download/LittleCMS-v2.15.0+0/LittleCMS.v2.15.0.x86_64-w64-mingw32.tar.gz"
