# Autogenerated wrapper script for LittleCMS_jll for x86_64-w64-mingw32
export liblcms2, linkicc, psicc, transicc

using JpegTurbo_jll
using Libtiff_jll
JLLWrappers.@generate_wrapper_header("LittleCMS")
JLLWrappers.@declare_library_product(liblcms2, "liblcms2-2.dll")
JLLWrappers.@declare_executable_product(linkicc)
JLLWrappers.@declare_executable_product(psicc)
JLLWrappers.@declare_executable_product(transicc)
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll, Libtiff_jll)
    JLLWrappers.@init_library_product(
        liblcms2,
        "bin\\liblcms2-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        linkicc,
        "bin\\linkicc.exe",
    )

    JLLWrappers.@init_executable_product(
        psicc,
        "bin\\psicc.exe",
    )

    JLLWrappers.@init_executable_product(
        transicc,
        "bin\\transicc.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
