# Autogenerated wrapper script for LittleCMS_jll for x86_64-linux-gnu
export liblcms2, linkicc, psicc, transicc

using JpegTurbo_jll
using Libtiff_jll
JLLWrappers.@generate_wrapper_header("LittleCMS")
JLLWrappers.@declare_library_product(liblcms2, "liblcms2.so.2")
JLLWrappers.@declare_executable_product(linkicc)
JLLWrappers.@declare_executable_product(psicc)
JLLWrappers.@declare_executable_product(transicc)
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll, Libtiff_jll)
    JLLWrappers.@init_library_product(
        liblcms2,
        "lib/liblcms2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        linkicc,
        "bin/linkicc",
    )

    JLLWrappers.@init_executable_product(
        psicc,
        "bin/psicc",
    )

    JLLWrappers.@init_executable_product(
        transicc,
        "bin/transicc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
